export class Post {
    constructor(uid, tit, bestTime, location, food, todo, ph, imagePath) {
      this.uid = uid;
      this.tit = tit;
      this.bestTime = bestTime;
      this.location = location;
      this.food = food;
      this.todo = todo;
      this.ph = ph;
      this.imagePath = imagePath;
    }
  }
  export const amritsarPost = new Post('1', 'Amritsar', 'Winter; Aug to Nov', 'Punjab, India', 'Chole Kulcha, Lassi', 
    'Golden temple, Jallianwala baug, wagha border', 'Nullam non lobortis justo. Integer suscipit aliquet justo pulvinar blandit. Ut dolor justo, lobortis ut sodales sit amet, tempor a tortor. Phasellus bibendum posuere tincidunt. Nam risus ex, laoreet a neque quis, lobortis eleifend nisl. Sed a sodales tellus, nec accumsan purus. In eu purus venenatis tortor iaculis mattis. Sed congue tortor felis, sit amet imperdiet arcu molestie nec. Vestibulum consectetur leo enim, dapibus varius velit condimentum vel. Phasellus vulputate sagittis eros, vitae rutrum elit dapibus ut. Phasellus lorem nisi, posuere vel orci vel, fermentum porttitor diam. Sed lacinia lacinia sapien. Nam id metus enim. Sed nec arcu pharetra, luctus lectus sagittis, pulvinar nulla. Mauris laoreet ex sit amet imperdiet lobortis. Ut quis risus nec lacus dictum faucibus. Mauris blandit purus vel risus scelerisque mollis. Fusce malesuada eleifend urna, condimentum pretium ligula. Phasellus lorem mauris, feugiat in tempus eu, maximus vel dui. Nam eu eros at leo rhoncus sodales. Ut at est sed est placerat vehicula. Aliquam erat volutpat. Vestibulum nec vestibulum risus. In nec elementum nibh, sed rhoncus ligula. Donec semper, metus quis ultricies accumsan, ex diam tristique risus, eu imperdiet felis mi eget felis. Etiam ut dolor tincidunt, egestas justo quis, auctor velit. Nullam sit amet nisi sit amet ex tincidunt imperdiet. Cras nec ipsum ligula. Phasellus tristique massa diam. Attended a friends wedding, Good music xd, Gian di lassi, Overnight wedding', "Images/Amritsar.jpg");
  export const kasolPost = new Post('2', 'Kasol', 'Mar to May, Oct to Nov', 'Himachal Pradesh, India', 'Aloo Paratha, Brownies xd', 
      'Waichin valley trek, Pulga woods and waterfall', 'Proin sit amet placerat arcu. Aliquam porttitor fermentum diam ac facilisis. Maecenas fringilla volutpat lectus vitae suscipit. Integer rhoncus tellus id massa semper, vitae dignissim nisi sollicitudin. Morbi tristique scelerisque bibendum. Duis iaculis ipsum sit amet odio malesuada congue. Nullam rhoncus lacus et posuere sodales. Donec scelerisque quam non tellus varius vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris laoreet ex sit amet imperdiet lobortis. Ut quis risus nec lacus dictum faucibus. Mauris blandit purus vel risus scelerisque mollis. Fusce malesuada eleifend urna, condimentum pretium ligula. Phasellus lorem mauris, feugiat in tempus eu, maximus vel dui. Nam eu eros at leo rhoncus sodales. Ut at est sed est placerat vehicula. Aliquam erat volutpat. Vestibulum nec vestibulum risus. In nec elementum nibh, sed rhoncus ligula. Donec semper, metus quis ultricies accumsan, ex diam tristique risus, eu imperdiet felis mi eget felis. Etiam ut dolor tincidunt, egestas justo quis, auctor velit. Nullam sit amet nisi sit amet ex tincidunt imperdiet. Cras nec ipsum ligula. Phasellus tristique massa diam. Went with a hinge match, challenging treks, good #', "Images/Kasol.jpg");
  export const mahabsPost = new Post('3', 'Mahabalipuram', 'Nov to Feb', 'Tamil Nadu, India', 'South Indian food', 
        'Fishermans beach, shore temple', 'Mauris laoreet ex sit amet imperdiet lobortis. Ut quis risus nec lacus dictum faucibus. Mauris blandit purus vel risus scelerisque mollis. Fusce malesuada eleifend urna, condimentum pretium ligula. Phasellus lorem mauris, feugiat in tempus eu, maximus vel dui. Nam eu eros at leo rhoncus sodales. Ut at est sed est placerat vehicula. Aliquam erat volutpat. Vestibulum nec vestibulum risus. In nec elementum nibh, sed rhoncus ligula. Donec semper, metus quis ultricies accumsan, ex diam tristique risus, eu imperdiet felis mi eget felis. Etiam ut dolor tincidunt, egestas justo quis, auctor velit. Nullam sit amet nisi sit amet ex tincidunt imperdiet. Cras nec ipsum ligula. Phasellus tristique massa diam. Surfing, Chill hostel - Rajlakshmi guesthouse',"Images/Mahabs.jpg");
  